# Setup
title:               eddrichjanzzenang
tagline:             My Own Webiste
description:         Some Amazing Description
url:                 http://yoururl.com
baseurl:             ''

# Plugins, Tags, Categories and Analytics  
plugins:
  - jekyll-gist
  - jekyll-feed
  - jekyll-admin
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap

# About/contact
author:
  name:              Eddrich Janzzen Ang
  url:               https://yoururl.com
  email:             you@gmail.com


paginate: 5
paginate_path: "posts/page:num/"
