# Setup
title:               Eddrich Janzzen
tagline:             My Own Webiste
description:         Personal Blog
url:                 https://eddrichjanzzen.github.io
baseurl:             ''

# Plugins, Tags, Categories and Analytics  
plugins:
  - jekyll-gist
  - jekyll-feed
  - jekyll-admin
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# About/contact
author:
  name:              Eddrich Janzzen Ang
  url:               https://eddrichjanzzen.github.io
  email:             eddrichang@gmail.com


paginate: 5
paginate_path: "posts/page:num/"
